# SPDX-License-Identifier: Apache-2.0
# Copyright Contributors to the ODPi Egeria project.
version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: monthly
    time: "03:00"
    timezone: "Etc/UTC"
  open-pull-requests-limit: 10
  reviewers:
  - planetf1
